### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/twitter#1]
Let me know when you're done with the code, tests and readme. I'll do a little code review, register the package on Packagist and start some automatic code quality checks.

**Comment by christophrumpel** [comment]
Awesome, thx a lot!

**Comment by christophrumpel** [comment]
ok great, I did a fix but now it is working, also the version problem with laravel dev is no longer a problem (somehow).

Guess I am ready for the review. One thing I already from @themsaid  is that the badges are missing. I will add them tonight after my flight or tomorrow. I also plan to add more features after the Laracon. Thx to you both!

**Comment by freekmurze** [comment]
Did the code review during Adam's workshop, but forgot to mention that here 😄
