### ISSUE TITLE
Add Laravel 11 support

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel-notification-channels/twitter#104]
Laravel 11 has been out for a few weeks. Can Laravel 11 be supported

![Capture](https://github.com/laravel-notification-channels/twitter/assets/25177538/37cd1ffe-299b-4fd3-967c-734e94dc6314)

**Comment by sts-ryan-holton** [comment]
Hoping to see an update soon, it's the last package in my composer json awaiting Laravel 11 :)

**Comment by sts-ryan-holton** [comment]
@christophrumpel Could https://github.com/laravel-notification-channels/twitter/pull/103 be merged?

**Comment by christophrumpel** [comment]
Just merged. Please give it a try and let me know if everything works.

**Comment by sts-ryan-holton** [comment]
Just updated. I'm running PHP 8.3. Everything is installable, and works to the extend of everything described in this issue apart from the error logged as described https://github.com/laravel-notification-channels/twitter/issues/101

**Comment by christophrumpel** [comment]
Thanks 🙏

I couldn't look more into that issue, sorry.
