### ISSUE TITLE
Per User Settings

### ISSUE THREAD

**Issue by aronduby** [laravel-notification-channels/twitter#13]
The system I'm building is tenated, so I need to be able to pull OAuth from each of the different models, instead of a site wide config. The site is tweeting as a team that is in the site, not the site itself. It looks like Laravel provides routing functions for the notifications, but this class isn't setup to use it. I can do some work and a PR to add it, but wanted to get your thoughts first.

First question is do you want this package to handle this use case?

If yes - the way I'm seeing it there's really two options: --we can either do specific with a fallback to the generic if the route function isn't specified--, or we have a way to switch between one or the other (either config or registering different providers or something). Do you have a preference? I think I prefer specific switch since there doesn't seem to be many use cases for the fallback, although fallback would probably be easier to code and maintain.

Any thoughts?

---

After thinking about it more, the fallback is not a good idea since it would be counter to how most, if not all, notifications work - that's just asking for trouble.

**Comment by ahmedash95** [comment]
Hi @aronduby , as a contributor in this repo may i ask you to show code example of what you want to do , cause i can't get the full picture well ?

**Comment by aronduby** [comment]
I'm not quite sure the best way to pull off the switch, but here's how the rest would happen, which is basically copy/paste from the Nexmo channel included by default.

In my tenanted model (for example the team)

```
class Team extends Model {
    public function routeNotificationForTwitter() {
        // return array with the twitter app settings or false if it's not set
    }
}
```

In the TwitterChannel

```
public function send($notifiable, Notification $notification)
{
    // could easily expand this to check a config setting or something
    if (! $settings = $notifiable->routeNotificationFor('twitter')) {
        return;
    }

    // now create the twitter oauth client and continue as normal
}
```

Then it's just the normal process laid out in the docs for sending the notification as the user

**Comment by ahmedash95** [comment]
@aronduby what about change twitter oAuth client credential on fly ? 

``` php
config()->set('services.twitter.access_token',$access_token);
config()->set('services.twitter.access_secret',$access_secret);

```

**Comment by aronduby** [comment]
then you can't easily skip a notifiable if they don't have it enabled

**Comment by ahmedash95** [comment]
i guess you should do this to get it work as you expected

``` php
class Team extends Model {
    public function routeNotificationForTwitter() {
         // check config data , if it's not set then return false
         return false;  
         // or change the twitter app settings
         config()->set('services.twitter.access_token',$access_token);
         config()->set('services.twitter.access_secret',$access_secret);
    }
}
```

**Comment by christophrumpel** [comment]
Hey @aronduby,

definitely open for more features. Will look into your cas that later today. I did some refactoring of the channel with a feature to send media too. I want to merge that in before any other addons. Thx @ahmedash95 for jumping in here too. I'll be back later today.

**Comment by ahmedash95** [comment]
@christophrumpel never mind 😄  .. PS. i love the new way of handling requests, Good job man!

**Comment by mpociot** [comment]
Instead of changing the config values on the fly, you could also extend the `TwitterServiceProvider` and modify the `boot` method to return tenant related configuration values:

https://github.com/laravel-notification-channels/twitter/blob/master/src/TwitterServiceProvider.php#L19-L24

**Comment by ahmedash95** [comment]
@mpociot, but he need to change the credentials based on row data of the model

**Comment by christophrumpel** [comment]
@ahmedash95 thx man! With the additional media parameter I felt we needed to change the code to provide the users a better experience. Glad you liked it.

@aronduby Just had a few minutes to check out your scenario. We really should add some functionality to make this work with user dependant data. I am definitely open for a PR or I could implement it myself if you don't want to. I am just leaving tomorrow morning for one week vacation, so I won't be able to help  before I will be back.

But of course @ahmedash95 and @mpociot can help here

**Comment by christophrumpel** [comment]
Sry guys for the late reply. It has been messy here. So I just looked into that problem.
My first solution would be like this. (not perfect yet, but working)
1. Dev adds a function to return user specific Twitter keys inside the notifiable model. I tested it with different settings in my config, but in real this data would probably come from the user's DB.

``` php
// Inside user model for example
public function routeNotificationForTwitter()
    {
        return [
            config('services.twitter.consumer_key2'),
            config('services.twitter.consumer_secret2'),
            config('services.twitter.access_token2'),
            config('services.twitter.access_secret2')
        ];
    }
```
1. In order to make the settings switch I would check for the user data and if it is given I create a new TwitterOAuth class with the new settings.

``` php
// Inside TwitterChannel
if ($twitterSettings = $notifiable->routeNotificationFor('twitter')) {
    $this->switchSettings($twitterSettings);
}
```

The switch could look something like this:

``` php
private function switchSettings($twitterSettings)
{
    $this->twitter = new TwitterOAuth(
        $twitterSettings[0],
        $twitterSettings[1],
        $twitterSettings[2],
        $twitterSettings[3]
    );
}
```

Place for improvement but maybe a good and working start =) What do you think guys?

**Comment by christophrumpel** [comment]
Any thoughts @mpociot or @themsaid ?

**Comment by christophrumpel** [comment]
Or maybe @freekmurze ?

**Comment by christophrumpel** [comment]
Another try =) @mpociot @themsaid @freekmurze 

What do you think of this approach? I really think there should be a per-user setting too.

**Comment by themsaid** [comment]
@christophrumpel I've used a similar in a cloned version of the pusher push notifications channel in which every tenant have his own pusher app credentials, so I'd say 👍

Sorry for the late reply :)

**Comment by christophrumpel** [comment]
Thx @themsaid ! No problem. Just wanted to get some feedback =) Then I will implement it and there will be time for changes afterwards too if there are better approaches or improvements =)

**Comment by christophrumpel** [comment]
Ok I did implement it. Anyone an idea how I can test that?

**Comment by christophrumpel** [comment]
Still not happy with the tests, but feel free to add a PR if you can and want to change that.

**Comment by aronduby** [comment]
Sorry I've mostly dropped off the face of the earth in this conversation, and it will only get worse in the coming months, but figured I would try to throw in real quick while I can.

@christophrumpel  I really like the [solution you have above](https://github.com/laravel-notification-channels/twitter/issues/13#issuecomment-250964832). The only quick thought I had was making it be able to do both global and per-user, but in that case it would be easy enough to create a "domain" model which does everything properly, which seems more inline with how the notification system works within Laravel.

Thanks for the great work!
