### ISSUE TITLE
Refactoring media twitter status

### ISSUE THREAD

**Issue by ahmedash95** [laravel-notification-channels/twitter#16]
Hi @christophrumpel  , based on what we talk here #13 for providing user experience . what about if we create a method for images like 

``` php
public function toTwitter($notifiable) {
    return new TwitterStatusUpdate(
        'Laravel notifications are awesome!',
    )->withImage([
        public_path('marcel.png'), public_path('mohamed.png'), public_path('freek.png')
    ]);
}
```

or as i prefer to create an twitter image class that allow us more functionality like validating images before post it or throw exception for some cases of uploading images

``` php
public function toTwitter($notifiable) {
    return new TwitterStatusUpdate(
        'Laravel notifications are awesome!',
    )->withMedia([
        new TwitterImage(public_path('marcel.png')), 
        new TwitterImage(public_path('mohamed.png')), 
        new TwitterImage(public_path('freek.png'))
    ]);
}
```

**Comment by christophrumpel** [comment]
Hey @ahmedash95 , sry for the delay. Work is always a mess after holidays =) Yeah I think it would be a good idea to add a method for the images. I am not sure if we need the image class too? Guess it is better for testing right? But feels a little bit more complex for the user to write?

**Comment by ahmedash95** [comment]
Hi @christophrumpel never mind , I hope you have enjoyed your holiday. i'm agree with the complexity for classes but i still see it's the best . but use method is fine with me too , so what's your final decision here ?

**Comment by christophrumpel** [comment]
I really did thx =) OK lets do the image class. Could you provide a PR? I am looking for a solution for the "per-user-setting" right now.

**Comment by ahmedash95** [comment]
No problem , wait my PR ;) .
