### ISSUE TITLE
PHP7 Required

### ISSUE THREAD

**Issue by aronduby** [laravel-notification-channels/twitter#17]
In TwitterStatusUpdate constructor you're type hinting message to a string which requires php 7 but in your composer you have 5.6.4

**Comment by christophrumpel** [comment]
Hey @aronduby, thx for the hint. Will fix that. I would like to make it a PHP7 package only. Are there any overall channel guidelines for that @mpociot @themsaid ?

**Comment by aronduby** [comment]
That seems like a bad idea given the only technical aspect that requires 7 is type hinting a single string and the package this is for is >= 5.6.4

**Comment by christophrumpel** [comment]
Yep you're. Using them a lot for my own stuff but it really makes no sense here. I will remove it.

**Comment by christophrumpel** [comment]
done.

**Comment by aronduby** [comment]
I saw this is fixed, but it's only in master, any chance you could tag it for composer?

**Comment by christophrumpel** [comment]
thx, done.

**Comment by aronduby** [comment]
thanks!
