### ISSUE TITLE
Handling character limits and URL wrapping

### ISSUE THREAD

**Issue by enygma** [laravel-notification-channels/twitter#19]
I briefly looked through the code for this but didn't immediately see anything that calculated the tweet length before sending it to the server. I discovered in some of my own work with the API that it does odd things when performing URL wrapping with the `t.co` links. This can change the character count from what it might seem.

This may not even be an issue as you might be okay with the failure handling catching that but I wanted to make you aware of it. Here's more information about Twitter character counts: [Twitter API docs](https://dev.twitter.com/basics/counting-characters).

**Comment by christophrumpel** [comment]
Great input! Do you want to provide a PR? If not I will take care of that. Thanks!

**Comment by christophrumpel** [comment]
So, just had some time to check it out. As you mentioned the current failure handling will tell you about the character limit right now. But I would see a benefit in not needing to call the Twitter API to get informed. Have you found a working way to count the message like Twitter does? Just looked it over and didn't see an easy way to do that. Have you?

**Comment by enygma** [comment]
I actually found a pretty cool library that seems to do a good job counting the characters as Twitter is expecting them: [kylewm/brevity](https://github.com/kylewm/brevity). I'm using it in one of my own projects right now and it seems to do well to shorten links and all according to those Twitter guidelines. I just make the message like normal, check the character count then, if it's too long, pull off some of it and put `...` after it.

**Comment by christophrumpel** [comment]
Thanks @enniel . I will check that out. Not sure yet if I want to include another package just for counting, but I will try it. It would a benefit handling this obvious error before sending to Twitter.

**Comment by christophrumpel** [comment]
So I took a look and decided to use that package. I merged a PR today and from now on the package is throwing an exception when the status update message is too long. I will also think about providing the "shorten" method from the brevity package. Thx @enygma and would be great if you could test it out too.
