### ISSUE TITLE
Send notification to user 

### ISSUE THREAD

**Issue by ahmedash95** [laravel-notification-channels/twitter#2]
I think twitter notification must be for chat messages also , something like 

``` php
return new TwitterMessage('ahmedash95','you have a notification in our app');
```

BTW, i could make a PR for this implementation

**Comment by christophrumpel** [comment]
Yeah you're right! Would appreciate a PR 👍

**Comment by christophrumpel** [comment]
So finally I'm back. I will check it out now. Sorry for having to wait that long.

**Comment by ahmedash95** [comment]
Never mind dude! , waiting your response :)
