### ISSUE TITLE
spacing content displayed on twitter

### ISSUE THREAD

**Issue by KDA809** [laravel-notification-channels/twitter#32]
`return (new TwitterStatusUpdate($blog->name .' https://google.com/'. $blog->slug))->withImage($image);`

i'm using this to display title content, link & image on twitter however the content & title seem to not space apart :/ how would i do this

**Comment by christophrumpel** [comment]
Hey @iiCe89 , can you show me what you mean? What is the result? No space between blog name and URL?

**Comment by KDA809** [comment]
for example this it what it would look like on twitter `TITLEIt is a long established fact that a reader will be distracted by the readable https://link.com `

so there is no break between `TITLE` and summary content

**Comment by christophrumpel** [comment]
ah ok, hm so how does you content look like? What are you using for the break?

**Comment by KDA809** [comment]
currently just this `$blog->name .' https://google.com/'. $blog->slug)` with the dots break each section but the URL seems to space from the summary it is just the Title & text that wont

**Comment by christophrumpel** [comment]
yeah but `title` and `text` come both from `$blog->name` right?

**Comment by KDA809** [comment]
$`blog->name . $blog-body .' https://google.com/'. $blog->slug)` like this apologie's

**Comment by christophrumpel** [comment]
Sry Im not sure if I get your correct. You did not put a space between name and body? Why don't you do it like that:
`return (new TwitterStatusUpdate($blog->name . ' ' . $blog->body .' https://google.com/'. $blog->slug))->withImage($image);`

**Comment by KDA809** [comment]
ah ok ! thank you will try that and update you :)

**Comment by KDA809** [comment]
works thank you

**Comment by christophrumpel** [comment]
👍
