### ISSUE TITLE
mediaIds array or collection?

### ISSUE THREAD

**Issue by huglester** [laravel-notification-channels/twitter#33]
Hello,

I am attaching media not from URL, but by id
Like:
```php
$tweet = new TwitterStatusUpdate($text);
$tweet->imageIds = collect([$twitter_media_id]);
```

But it says it should be an array, in the var declaration.
```php
    /**
     * @var  array
     */
    public $imageIds;
```

So probably this should be changed to implode(',', $this->imageIds);
or change to Collection? 
```

if ($this->imageIds) {
            $body['media_ids'] = $this->imageIds->implode(',');
        }
```

thanks

**Comment by christophrumpel** [comment]
Yeah you're right. I will change the type to collection in the docblock. This way the code can stay the same 👍

**Comment by christophrumpel** [comment]
Fixed with the latest PR.
