### ISSUE TITLE
Undefined property: stdClass::$media_id_string

### ISSUE THREAD

**Issue by robertnicjoo** [laravel-notification-channels/twitter#40]
Hi,

when i try to run my code i get

```php
Undefined property: stdClass::$media_id_string
```
on
```php
 $post->notify(new \App\Notifications\PostPublished($post));
```

here is my notification function:

```php
public function toTwitter($post)
    {
        $title = $post->title;
        $slug = $post->slug;
        $image = $post->image;
        return (new TwitterStatusUpdate($title ."\n https://domain.co/blog/". $slug))->withImage('http://domain.co/storage/images/'.$image);
    }
```

any idea?

**Comment by christophrumpel** [comment]
Hey, my first guess is that it does not work with online hosted images. They must be local ones.

**Comment by robertnicjoo** [comment]
@christophrumpel  i am working on local, first i only used `$image` it gave error that cannot find image so i put full address

**Comment by robertnicjoo** [comment]
@christophrumpel as for testing i removed `image` part and here is what i get now:


```php
Couldn't post Notification. Response: Bad Authentication data.
```

**Comment by christophrumpel** [comment]
This error is from your Twitter. Have you checked your Twitter credentials?

**Comment by robertnicjoo** [comment]
you mean my twitter app? `which part should i check?`

**Comment by christophrumpel** [comment]
Have you checked the installation instructions here? https://github.com/laravel-notification-channels/twitter

You need to add these to the `config/services.php` file:

```
'twitter' => [
	'consumer_key'    => env('TWITTER_CONSUMER_KEY'),
	'consumer_secret' => env('TWITTER_CONSUMER_SECRET'),
	'access_token'    => env('TWITTER_ACCESS_TOKEN'),
	'access_secret'   => env('TWITTER_ACCESS_SECRET')
]
```

And you need to add those values to your `.env` file. Have you done that?

**Comment by robertnicjoo** [comment]
I've done that already.

**Comment by christophrumpel** [comment]
And the Twitter credential values in your `.env` file are correct?

**Comment by robertnicjoo** [comment]
yes, 5+ times i checked them
![dddd](https://user-images.githubusercontent.com/8672823/39661634-f142444c-507e-11e8-9c85-f8efa78645b4.png)

**Comment by christophrumpel** [comment]
Hmm strange. Jsut checked it for myself and it still works. Maybe try to generate new keys or to create a new Twitter app. It must be something on the Twitter side.

**Comment by robertnicjoo** [comment]
I created new app and same result :(

```php
Couldn't post Notification. Response: Bad Authentication data.
```

**Comment by christophrumpel** [comment]
hmm do you got another Twitter user you can try? You could also try to google this Twitter API error to find a solution. Since I can reproduce it, I guess I can't help here sry.

**Comment by robertnicjoo** [comment]
Thanks anyway.

**Comment by christophrumpel** [comment]
NP. Let me know if you find out more.

**Comment by robertnicjoo** [comment]
@christophrumpel  I solved the issue and just to let you know, all i had to do was

```php
php artisan cach:clear
// then
composer dump-autoload
```

Also if someone else some day ends up here can double check their `env` values by tinker like:

```php
php artisan tinker
// then
env('TWITTER_ACCESS_SECRET')
and so on...
```
If return the value that is set in `env` file they are good to go.

**PS:** Another thing maybe you like to mention in documents is that for image you must provide full address `$post->image` is not enough and returns error of can't getting file, should be like `http://domain.co/storage/images/$post->image`

Have fun.

**Comment by christophrumpel** [comment]
Thx a lot for mentioning it! I will add it to the docs. Glad it works now.

**Comment by SandhyaLatha** [comment]
@christophrumpel  @robertnicjoo  hi i am also encountered with same error while creating subtitles [ref](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-subtitles-create).
my subtitle file git uploaded with media/upload endpoint and returned success response then i called subtitle creation endpoint which is returning undefined index and undefined property error. Any thoughts on this..
