### ISSUE TITLE
Support for Laravel 5.7?

### ISSUE THREAD

**Issue by azimidev** [laravel-notification-channels/twitter#41]
Hi guys, thanks for this great package.

I'm running into an error when upgrading to Laravel 5.7.
Is it possible to fix it in Packagist so we can pull?

Thanks

**Comment by christophrumpel** [comment]
Hey, your're welcome. I just merged it. Please try again and let me know if it works.

**Comment by azimidev** [comment]
Thank you @christophrumpel
