### ISSUE TITLE
Multiple Twitter Accounts

### ISSUE THREAD

**Issue by bradders** [laravel-notification-channels/twitter#43]
First up, awesome package! 🙌 

I've hit a use case where I want to be able to switch the Twitter account my app posts from. Super quick, high level explanation, but my app has regions and each region has its own Twitter account. I'm looking/hoping to have multiple entries in my env file corresponding to each twitter account and then being able to specify which to post to.

**Comment by bradders** [comment]
@christophrumpel  Sadly my PHP is somewhat suspect, else I'd just in and submit a PR. But pseudo-code speaking, maybe the env fields (token, secret, key) can be passed in or overridden?

**Comment by christophrumpel** [comment]
Thanks 😀I will give it a look today. Maybe I come up with a possible solution. Would be a nice add-on.

**Comment by lars-fomin** [comment]
@bradders you can implement **routeNotificationForTwitter** method in your model that uses Notifiable trait which should return an array with credentials based on the region

**Comment by christophrumpel** [comment]
Hey, so I just checked it and it should already be possible. With all Laravel notifications, we have `routeNotificationsForChannel` methods, which you can use inside your notifiable model like a user. https://laravel.com/docs/5.7/notifications#customizing-the-recipient

In my package, I'm already checking for this method `routeNotificationForTwitter`. So you can use this method and decide on a `user-level` which settings to use. In this method, you need to return the new tokens then as an array. Need to try it myself and update the docs to make it clear.

**Comment by christophrumpel** [comment]
Yep just tested it again. Works like that:

```
public function routeNotificationForTwitter($notification)
    {
        return [
            'TWITTER_CONSUMER_KEY',
            'TWITTER_CONSUMER_SECRET',
            'TWITTER_ACCESS_TOKEN',
            'TWITTER_ACCESS_SECRET',
        ];
    }
```

This will now override the keys from the env file. You can now, for example, save two pairs of keys in your env file and depending on the user you want to send something, decide which keys to load from this method. I will add that to the docs as well.

**Comment by christophrumpel** [comment]
Have you tried it @bradders ?

**Comment by bradders** [comment]
@christophrumpel Sorry, I haven't had chance yet. Currently wallowing in Twitter support hell trying to get my second Twitter app past the request stage! 

It looks good though, I'll check it out as soon as possible! 🙌

**Comment by christophrumpel** [comment]
oh I see. All the best! :-) I will close this cause I think it is solved with the provided information. If you run into any problems just open it again.
