### ISSUE TITLE
laravel 5.8 support

### ISSUE THREAD

**Issue by azimidev** [laravel-notification-channels/twitter#49]
Hey, guys, can u update this package to be compatible to 5.8 and also update it in Packagist as well?

Thx

**Comment by christophrumpel** [comment]
Hey, I created a new release with support for Laravel 5.8. It just needs to get updated on Packagist, then it will be available.

**Comment by christophrumpel** [comment]
It is now available through the new version 👍

**Comment by MoatazAbdAlmageed** [comment]
please check I'm using 5.8 but I got this error here https://github.com/laravel-notification-channels/twitter/issues/60
