### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by jeffwa** [laravel-notification-channels/twitter#51]
Hi,

Will this package be updated for Laravel 6.0? 

Thanks

**Comment by christophrumpel** [comment]
Hey, it will for sure. But maybe a couple more days before I can do it. You could also help out with a PR?

**Comment by jeffwa** [comment]
Added a PR late last night. Forgot to ping you. https://github.com/laravel-notification-channels/twitter/pull/52

**Comment by atymic** [comment]
Support added in #52
