### ISSUE TITLE
no usage information

### ISSUE THREAD

**Issue by azizoid** [laravel-notification-channels/twitter#57]
Usage information says now to install but not how to use

what code should i post in Model, what in Controller? nothing

**Comment by christophrumpel** [comment]
Hey. What information are you missing? Please check the Laravel docs for information about how to use Laravel notifications: https://laravel.com/docs/5.7/notifications#sending-notifications

Maybe I should add that to the readme to make that more clear. Does this already help you?

**Comment by azizoid** [comment]
Thank you for answering. I figured that out. but have no idea how. 
For example it took me quite long to find out this part of code in Controller will work.
```
$tmp = Quran::select(*)->get()->random();
Notification::send($tmp, new TweetAyahNotification('Read'));
```

**Comment by azizoid** [comment]
Notification file
Model file
Controller file

if you just put example codes to all of these files. it would take us faster to use your code. But instead you send us to read the documentation. I was very close to give up and not to use it. 

Have a little bit of empathy, not all of us are as good as you, and some things that are easy for you, we might not get that easily :)

Any way thank you for the code

**Comment by christophrumpel** [comment]
Thanks for your feedback. I have to say it is the first time I get this kind of feedback but I get it. I will try to improve the docs. Thanks for taking the time to mention it 👍
