### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated on PHP 7.4

### ISSUE THREAD

**Issue by Aurelien-NGT-11** [laravel-notification-channels/twitter#58]
Hello,

As required by composer.json, "abraham/twitteroauth" is used in its 0.9.2 version, which accesses arrays with curly braces, a feature deprecated since PHP 7.4.

https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.array-string-access-curly-brace
> Array and string offset access using curly braces
The array and string offset access syntax using curly braces is deprecated. Use $var[$idx] instead of $var{$idx}.

It has been fixed with [this](https://github.com/abraham/twitteroauth/commit/7f4c3e6b6526a940b11ee293b2eb933ec8ed292e) commit.
You should bump abraham/twitteroauth dependency to fix the usage of this package with PHP 7.4

Thank you

**Comment by christophrumpel** [comment]
Hey, thanks for the hint. Have you tried it with a newer version of the package yourself already?

**Comment by Aurelien-NGT-11** [comment]
Hi,

I've upgraded abraham/twitteroauth from version 0.9.2 to 1.1.0 myself.
It's working on production and unit tests passed successfully.

**Comment by christophrumpel** [comment]
thanks! I will update it today or tomorrow 👍

**Comment by christophrumpel** [comment]
Hey, I just release a new version. Please let me know if it works for you.

**Comment by Aurelien-NGT-11** [comment]
Hey,

It's working well 👍

Thanks for the quick update
