### ISSUE TITLE
Adding links to tweets

### ISSUE THREAD

**Issue by Adam-78** [laravel-notification-channels/twitter#59]
Hi,

How do you add links inside tweet when using `TwitterStatusUpdate`

The following renders as escaped html on twitter:

      return new TwitterStatusUpdate( '<a href="http://example.com">http://example.com</a>');

**Comment by Adam-78** [comment]
Figured it out...no need to include html markup.

**Comment by christophrumpel** [comment]
Sry just saw the issue. Glad it worked out for you 👍

**Comment by joantp** [comment]
Is there a way to send markup links? ... I'd like to send something like:

 `<a href="http://www.example.com>This is My Example</a>`
