### ISSUE TITLE
Bad URL: unable to shorten

### ISSUE THREAD

**Issue by junaidrasheed** [laravel-notification-channels/twitter#63]
First of all, thanks for this amazing package. I've been using it for quite some time now to send twitter DMs. My message content always contains one or more URLs in it. These URLs could be to other tweets or external websites. I'm facing an issue of Bad URL: unable to shorten : (Already shorten URL) exception from time to time and I was wondering if there is any way to get around shortening these types of links?

Thanks.

**Comment by christophrumpel** [comment]
Hey, thanks a lot!

Hm never had that issue. Can I reproduce it somehow?

**Comment by junaidrasheed** [comment]
Errors are coming from app running in production. I can only provide the stack trace if that helps

`{
    "class": "NotificationChannels\\Twitter\\Exceptions\\CouldNotSendNotification",
    "message": "Couldn't post notification. Response: There was an error sending your message: Bad URL, unable to shorten: https://t.co/wtuKq74.",
    "code": 0,
    "file": "/var/www/html/tie-vision/vendor/laravel-notification-channels/twitter/src/Exceptions/CouldNotSendNotification.php:15",
    "trace": [
        "/var/www/html/tie-vision/vendor/laravel-notification-channels/twitter/src/TwitterChannel.php:39",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:146",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:105",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php:19",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:107",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php:54",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php:74",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Container/Util.php:36",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Container/Container.php:590",
        "/var/www/html/tie-vision/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94",
`

**Comment by christophrumpel** [comment]
Is this the URL you want to send? https://t.co/wtuKq74 and hot did you shorten it?

**Comment by junaidrasheed** [comment]
Yes this is the URL. I'm not shortening it on my end. This is how I received it from a 3rd party. And when I try to send a twitter DM based on the API response it caused the issue.

**Comment by christophrumpel** [comment]
Hm I see. It also didn't work for me. I haven't found the issue yet. Will give it a try next week.

**Comment by junaidrasheed** [comment]
Just following up. Have you find anything?

**Comment by christophrumpel** [comment]
Hey, sry not yet. I didn't had time yet, because my week is quite busy. Will try to see if someone else can help meanwhile.

**Comment by johannesnagl** [comment]
I guess you simply can't send t.co links through the API (that don't exist). 

I would assume that you 

a) need to send the expanded url (try to make an curl/guzzle call to see where the link is redirecting you to). you can then use the expanded url in your direct message.
b) just test if a working t.co link works. in case yes, Twitter is only allowing you to send valid t.co links. then also check if a link is returning a 200 OK with curl/guzzle. if yes, all fine :).

so seems unrelated to this library here.

**Comment by peterpan666** [comment]
I was about to send the same thought as @johannesnagl.

Maybe it's because of the ending dot because it appears in the error message...

**Comment by mathiasmoser** [comment]
yes - as @johannesnagl said you can't post tweets with invalid .co urls in the content - if you try to post a tweet without the package - eg directly via the twitter.com website you will also get an error:

Example:
i try to tweet your invalid url:
https://t.co/wtuKq74

error-response (HTTP 400) from twitter api: (POST https://api.twitter.com/1.1/statuses/update.json)
{"errors":[{"code":408,"message":"The given URL is invalid."}]}

**Comment by christophrumpel** [comment]
Thanks @johannesnagl , @peterpan666 and @mathiasmoser 👍 I didn't see that the page does not exist. Guess this explains it. 

@junaidrasheed guess you have to talk to your third party or need to check on your side if the URL is valid before using this package.

**Comment by junaidrasheed** [comment]
Thanks everyone for helping out. Let me check with my 3rd party resource for links like these.

Thanks again,
