### ISSUE TITLE
How can I get the tweet_id sent?

### ISSUE THREAD

**Issue by sotoplatero** [laravel-notification-channels/twitter#65]
It is possible to get tweet_id of the tweet that was sent as notification?

**Comment by christophrumpel** [comment]
Hmm not sure at the moment. I'd need to check that but can't do it before next week. I will get back to you.

**Comment by christophrumpel** [comment]
Hey, so I looked into it today. It seems you cannot return anything from a Laravel notification, but you can use events.

Laravel will send different notification events https://laravel.com/docs/master/notifications#notification-events. I changed the code of the package that the Twitter API response will be in this event. So you just need to listen for an event like "NotificationSent" and then you can find the tweet id.

Does this help?

**Comment by sotoplatero** [comment]
sorry for not giving an answer. I'm going to check the notification events. Thank you very much,  is incredible your work
