### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/twitter#66]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by owenvoke** [comment]
Looks like this can be closed as [v5.0.0](https://github.com/laravel-notification-channels/twitter/releases/tag/v5.0.0) supports it. 👍🏻

**Comment by christophrumpel** [comment]
Right, thanks :-) 👍
