### ISSUE TITLE
 Undefined property: stdClass::$errors

### ISSUE THREAD

**Issue by kejubayer** [laravel-notification-channels/twitter#69]
## I'm trying to create a status. But when I hit the URL, I get the error "Undefined property: stdClass::$errors"
My code below. 

```
 public function via($notifiable): array
    {
        return [TwitterChannel::class];
    }

    public function toTwitter($notifiable)
    {

        return new TwitterStatusUpdate('Laravel notifications are awesome!');
    }
```
### route
```
Route::get('/test', function () {
    Notification::route(\NotificationChannels\Twitter\TwitterChannel::class,'')
        ->notify(new TwitterNotification());
});
```
In composer.json
```
  "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.9.2",
        "laravel-notification-channels/twitter": "^4.1.0",
        "laravel/tinker": "^2.0"
    },
```

**Comment by christophrumpel** [comment]
Was this working before or is this a new install? And can you show the full error message, please?

**Comment by kejubayer** [comment]
This is a new install. 
Error page screenshots.
![screencapture-twitter-jubayer-twitter-2020-09-28-12_05_09](https://user-images.githubusercontent.com/47379243/94396118-0b7cbd80-0183-11eb-9f21-3c25c493a0d5.png)

**Comment by christophrumpel** [comment]
Can you try to send a notification via a model like a user please and tell me if that works?

```php
$user = new User();
$user->notify(new TestNotification());
```

**Comment by kejubayer** [comment]
Sorry sir, It's showing the same error.
`Route::get('/twitter', function () {  $user = new User();   $user->notify(new TestNotification());  });`
![2020-09-29](https://user-images.githubusercontent.com/47379243/94470628-c0e25c00-01e9-11eb-9b23-f357034c7c74.png)

**Comment by leganz** [comment]
@kejubayer could you check the api respond? 

like by changing the code => ./vendor/laravel-notification-channels/twitter/src/Exceptions/CouldNotSendNotification.php

```php
   /**
     * @param $response
     * @return CouldNotSendNotification
     */
    public static function serviceRespondsNotSuccessful($response)
    {
        dd($response);
        $responseBody = print_r($response->errors[0]->message, true);

        return new static("Couldn't post notification. Response: ".$responseBody);
    }
```

It looks like that the response doesn't follow the expected behavior....

**Comment by leganz** [comment]
@kejubayer  => ok i think i found the problem!
Please check if your access_token / secret pair is allowed to post. 

I created  a PR #70 to fix that.
Hope that helps you.

**Comment by kejubayer** [comment]
Thank You, I got the real error. And the problem is solved.

**Comment by leganz** [comment]
Was it the insufficient permission issue or something else?

**Comment by kejubayer** [comment]
Yes, It was permission issue.
