### ISSUE TITLE
Markup links

### ISSUE THREAD

**Issue by joantp** [laravel-notification-channels/twitter#73]
As an extension of this issue, https://github.com/laravel-notification-channels/twitter/issues/59#issue-568831560, I wonder if it is possible to send a markup link like:

`<a href="http://www.myexample.com">My Example</a>` 

giving <a href="http://www.example.com">My Example</a> as result.

I've tried nl2br, htmlentities,htmlspecialchars ... but no luck.

**Comment by christophrumpel** [comment]
Hey,

hmm is this even possible in Tweets? From what I know, I don't think this is possible.

**Comment by simpledev** [comment]
@joantp You don't need to include HTML markup to your links. Your links will be automatically tagged if twitter notifications are sent from a production server, but not if sent from a local environment. From my own experience ...

**Comment by joantp** [comment]
> @joantp You don't need to include HTML markup to your links. Your links will be automatically tagged if twitter notifications are sent from a production server, but not if sent from a local environment. From my own experience ...

Yes, you are right. You can send just the string 'www.example.com' and twitter tags it automatically as www.example.com. But I think it is not possible to get a <a href="http://www.example.com">example</a> format.

**Comment by christophrumpel** [comment]
Ah ok got it, yeah I'm pretty sure this is not possible with normal tweets and therefore also not possible with my package.
