### ISSUE TITLE
Reply to tweet feature request

### ISSUE THREAD

**Issue by amiranagram** [laravel-notification-channels/twitter#75]
I want to be able to reply to a tweet with status update. Very useful with Twitter bots that have a Laravel back-end.

I'm willing to code this.

**Comment by christophrumpel** [comment]
Hey, sry I missed this issue. So you mean like you provide a status update id (= tweet) and the notification should be a reply to that tweet?

**Comment by amiranagram** [comment]
@christophrumpel Exactly. Something like:

```php
public function toTwitter($notifiable)
{
    return (new TwitterStatusUpdate('Laravel notifications are awesome!'))
        ->inReplyTo($this->tweet_id);
}
```

**Comment by christophrumpel** [comment]
I like the idea. Did you maybe already check how it could work technically? Would you want to work on a PR on that?

**Comment by amiranagram** [comment]
I know how it works. I built a Twitter bot last year that I already abandoned. 😅 

> Would you want to work on a PR on that?

Sure.
