### ISSUE TITLE
Only Twitter API v1.1, API v2 should be implemented as well.

### ISSUE THREAD

**Issue by aviavee** [laravel-notification-channels/twitter#83]
Only possible to use API v1.1 which after Nov. 2021 needs elevated access in the twitter developer portal, a switch to API v2 or a ability to choose API version would be greatly appreciated.

**Comment by christophrumpel** [comment]
Hey, do you know when 1.1 will be deprecated? What does "elevated access" mean?

But overall a switch to API v2 is needed indeed. Do you want to work on a PR?

**Comment by aviavee** [comment]
I have not found any information regarding removal of API v1.1, but the elevated access is granted through a manual assessment process of your application. Elevated access also have other rate limits and different endpoints.  After Nov. 2021 the default API for all users are v2. there are som limitations however, eg. media upload is not implemented into v2 yet. Still ongoing development.
I don't have the necessary skills to work on a project like this, sorry.

**Comment by christophrumpel** [comment]
Ok thanks @kredittkort1 👍

**Comment by christophrumpel** [comment]
This package and v8 were updated to the new Twitter API 👍
