### ISSUE TITLE
Twitter v2 now breaks this package by default

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel-notification-channels/twitter#86]
I've just set up Twitter notifications that I need in my project, after trying it out, and getting an error in the `TwitterDirectMessage.php` file it's clear that when adding a custom log into this file that the current version of the package is unsupported with Twitter v2:

As per [this](https://github.com/laravel-notification-channels/twitter/issues/83) earlier in the year, this has now indeed come into affect, and in addition, I cannot upgrade my application past version 5 as version 6 requires PHP 8.

Any chance you could get some support in for both versions? my error I'm getting:

> {"user":"{\"errors\":[{\"message\":\"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you\\u2019ll need to apply for Elevated access via the Developer Portal. You can learn more here: https:\\/\\/developer.twitter.com\\/en\\/docs\\/twitter-api\\/getting-started\\/about-twitter-api#v2-access-leve\",\"code\":453}]}"}

**Comment by christophrumpel** [comment]
Hey, sorry to see you running into this issue. I can't take a look myself currently, I will see if I find someone else who can help here in the meantime.

**Comment by sawirricardo** [comment]
Hi @sts-ryan-holton what support you're looking for specifically? Maybe I can help @christophrumpel to take a look. Also, maybe don't you think you want to try to get the elevated access?

**Comment by sts-ryan-holton** [comment]
@christophrumpel Thanks for getting back to me so quickly! Really value the support of these notification channels, projects like mine rely on these and great support.

@sawirricardo I've recently applied for elevated access and have just found out that this has been approved, so I'll be able to try this out later.

If this works as I intend I do have some other questions but since they're not related to the discussion of Twitter v2 I'll open some new Github issues once I've played around a bit! :)

**Comment by sawirricardo** [comment]
looking forward to your feedback with that elevated access @sts-ryan-holton  👍

**Comment by sts-ryan-holton** [comment]
@sawirricardo Ok, so elevated access now works in getting to Twitter, but when attempting to post, I'm using `TwitterDirectMessage`, I get the following error:

> NotificationChannels\Twitter\Exceptions\CouldNotSendNotification: Couldn't post notification. Response: Read-only application cannot POST.

After a little googling, one [suggestion](https://twittercommunity.com/t/read-only-application-cannot-post/165806) is to enable **Read and write and Direct message**, which I've just done, and still get the error.

**Comment by sts-ryan-holton** [comment]
Ignore the above comment, I'll keep it for reference though, **need to regenerate keys** after enabling **Read and write and Direct message** in order for it to work as intended, I'll close this issue 👍

**Comment by sawirricardo** [comment]
Glad to hear that it works @sts-ryan-holton

**Comment by christophrumpel** [comment]
Thank you, guys. Just quickly looked through, so the issue is solved? Is there something we should update the documentation of this package?

**Comment by sawirricardo** [comment]
I think all is fine since it's on the twitter side err rather than the package...

**Comment by christophrumpel** [comment]
Thanks for helping @sawirricardo 👏
