### ISSUE TITLE
Returning Twitter class as string in via method (TwitterChannel:::class)

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel-notification-channels/twitter#87]
👋 Opening another issue here regarding the implementation of the Twitter channel in the `via` method for my notification class. Notifications are now able to send if I simply just `[TwitterChannel::class]` in my `via` method, but my application allows users to effectively have "notification types" and as such are saved onto my `User` model and look like this:

```json
{
    "dns": {
        "changed": ["nexmo", "database", "mail", "twitter"]
    },
    "ssl": {
        "expiry": ["nexmo", "mail"]
    },
    "domains": {
        "expiry": ["nexmo", "database"]
    },
    "monitors": {
        "up": ["database", "mail"],
        "down": ["database", "mail", "twitter"]
    }
}
```

This presents the challenge of including Twitter since I'd ideally just like to include a `twitter` string in my notification channel since this is ultimately rendered into the view as checkboxes.

When I try to use `twitter` as a string, unlike the Nexmo, Database, Slack and Mail drivers, the Twitter notification channel throws an error:

> InvalidArgumentException: Driver [twitter] not supported.

Each notification is my application links up to one of my `via` objects, for example: my monitor `MonitorDown` notification links up to `monitors->down` as JSON, I have other business logic that I need to perform to, such as being able to dynamically push or remove Twitter from my notification preferences.

**Is there a simple workaround or modification** I can add so that the `TwitterChannel::class` is initialised and then if there's a `twitter` string in my notification preferences for that notification it then runs since we have the `toTwitter` method?

```php
/**
 * Get the notification's delivery channels.
 *
 * @param  mixed  $notifiable
 * @return array
 */
public function via($notifiable)
{
    $preferences = json_decode($notifiable->notification_preferences);

    if (!$notifiable->is_subscribed) {
        $preferences->monitors->down = array_merge(array_diff($preferences->monitors->down, [
            'nexmo', 'discord', 'twitter'
        ]));
    }

    // desired outcome
    return ['twitter'];

    // must come from here
    return $preferences->monitors->down;
}
```

_P.S: I have several other notifications I need to apply this to_

**Comment by christophrumpel** [comment]
Hey, I see what you mean.

Have you checked the other notification channels? Maybe one of them has solved the "issue" already? That's what I would check first.

Second thought: maybe you can also check how Laravel is doing it for its channels like "mail" etc. Guess they are also using a class behind. Maybe there's something we can add to this package to make it work too.

**Comment by sts-ryan-holton** [comment]
@christophrumpel managed to find a solution on Laracasts whereby creating a custom `NotificationServerProvider` and including the various channels in there allows to convert the channel name to whatever is needed, example:

```php
<?php

namespace App\Providers;

use NotificationChannels\Twitter\TwitterChannel;
use NotificationChannels\Discord\DiscordChannel;
use NotificationChannels\Webhook\WebhookChannel;
use Illuminate\Notifications\ChannelManager;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\ServiceProvider;

class NotificationServiceProvider extends ServiceProvider
{
    /**
     * All of the container singletons that should be registered.
     *
     * @var array
     */
    public $singletons = [
       'twitter' => TwitterChannel::class,
       'discord' => DiscordChannel::class,
       'webhook' => WebhookChannel::class
    ];

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        Notification::resolved(function (ChannelManager $service) {
            $service->extend('twitter', function ($app) {
                return $app->make('twitter');
            });

            $service->extend('discord', function ($app) {
                return $app->make('discord');
            });

            $service->extend('webhook', function ($app) {
                return $app->make('webhook');
            });
        });
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
```

**Comment by christophrumpel** [comment]
Awesome! Thanks for sharing the result too 👏
