### ISSUE TITLE
This package now breaks authentication when creating new apps

### ISSUE THREAD

**Issue by Adam-78** [laravel-notification-channels/twitter#94]
This package now break when you create a new app in the twitter developer console.

To replicate:

Create a standalone app in the twitter developer console so that we can still use the v1 twitter endpoints.
The generated access key will default to read only permissions, so to enable read write permissions update the user authentication settings for the app to Read and write and Direct message. Set the type of app to web app
Regenerate the keys
Add the keys inside your laravel .env file.

If you then test the package using a laravel application you'll get error

       [2023-04-28 15:25:06] local.ERROR: Couldn't post notification. Response: Invalid or expired token. {"exception":"[object] (NotificationChannels\\Twitter\\Exceptions\\CouldNotSendNotification(code: 0): Couldn't post notification. Response: Invalid or expired token. at C:\\project\\vendor\\laravel-notification-channels\\twitter\\src\\Exceptions\\CouldNotSendNotification.php:17)

Not sure if your package should include sending a bearer token to authneticate

**Comment by christophrumpel** [comment]
Hey,

ok strange, tried it myself and for me it works. Do you see anything I could have done differently?

**Comment by Adam-78** [comment]
Hi,

Can you confirm if you've followed the following steps to replicate:

1.  Sign into https://developer.twitter.com
2.  Under standalone apps create a new app  https://developer.twitter.com/en/portal/apps/new
3.  Copy the generated api and api secret keys to your laravel env file - these are defined as TWITTER_CONSUMER_KEY and 
TWITTER_CONSUMER_SECRET in my env file
4. Go to the user authentication settings for the app and apply the following settings:
       - Set the app permissions to 'Read and write and Direct message'
       - Set type of app to 'Web App, Automated App or Bot'
       - Add a callback url and website url under the App Info settings otherwise it won't let you save the cahnges - I just added a dummy callback url.
5. Save the settings - this will create an ouath2 client id and client secret.
6. Go into the 'keys and token' tab and under the 'Authentication tokens' section generate the access token and secret and copy them to you env file. I save these as TWITTER_ACCESS_TOKEN and TWITTER_ACCESS_SECRET in my env file.

These are the only keys I'm using. I don't use any of the oauth2 client id and secret keys. Is there anything else I'm suppose to configure for the laravel notification channels to work?

Note before I follow the above steps I've downgraded to the FREE access. I now get the following error:

    Couldn't post notification. Response: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal.

So correct me if i'm wrong, maybe it looks like even with the new free twitter access level and setting up a standalone app we are restricted to using the v2 endpoints which this package currently doesn't support.

**Comment by christophrumpel** [comment]
Hey, there is now a new version "8.0" that works with the new V2 API. Can you please try it only your side with that too?

**Comment by irsyadadl** [comment]
No chris, it doesnt work too.

What I got when I try to post a tweet is:
```bash
NotificationChannels\Twitter\Exceptions\CouldNotSendNotification: Couldn't post notification. Response: When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal. in /../vendor/laravel-notification-channels/twitter/src/Exceptions/CouldNotSendNotification.php:17
```

**Comment by irsyadadl** [comment]
If we use twitter API v2, is there anything we must add ? Or this is enough?

```bash
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ACCESS_TOKEN=
TWITTER_ACCESS_SECRET=
```

I've confused, it always said that I have to use a kyes and tokens.
