### ISSUE TITLE
Intermittent ErrorException: Attempt to read property "media_id_string" 

### ISSUE THREAD

**Issue by topclaudy** [laravel-notification-channels/twitter#99]
ErrorException: Attempt to read property "media_id_string" on null in /var/www/stocktreats.com/vendor/laravel-notification-channels/twitter/src/TwitterChannel.php:82

This sometimes happens when posting tweet with image (just one image in my case)

**Comment by christophrumpel** [comment]
Can you please give a bit more details?

Are you already using v8?

**Comment by topclaudy** [comment]
> Can you please give a bit more details?
> 
> Are you already using v8?

Yes! It happens on v8

**Comment by christophrumpel** [comment]
Ok thx. Any chance you can dump the Twitter call response? Should be this one:
https://github.com/laravel-notification-channels/twitter/blob/master/src/TwitterChannel.php#L80

**Comment by topclaudy** [comment]
Given the error message, I think the call response is null in case of error. Do you want me to dump the response in case of success?

**Comment by njoguamos** [comment]
Experiencing the same error when I try to post a tweet that has an image. 

`Undefined property: stdClass::$media_id_string`

<img width="1153" alt="Screenshot 2023-07-23 at 19 43 40" src="https://github.com/laravel-notification-channels/twitter/assets/29255728/b6a8be87-9ed1-4977-b388-402f26a5a116">

**Comment by njoguamos** [comment]
I dumped out the response from line 82. Here is the response.

<img width="770" alt="Screenshot 2023-07-23 at 20 03 09" src="https://github.com/laravel-notification-channels/twitter/assets/29255728/0254aff0-63b5-4190-ad9a-215b2824b6a0">

**Comment by christophrumpel** [comment]
Thanks. Can you confirm, that just sending a text tweet works?

**Comment by njoguamos** [comment]
For some strange reason, the text tweets are going through, but I cannot see them on the Twitter profile page.

When I retry the same text, I get the following error

`Couldn't post notification. Response: You are not allowed to create a Tweet with duplicate content.`

**Comment by njoguamos** [comment]
I have managed to fix the issues by regenerating the credentials.

**Comment by topclaudy** [comment]
I also regenerated credentials before opening this issue, and the error persists (intermittently)

**Comment by topclaudy** [comment]
No problems with text-only tweets.

**Comment by njoguamos** [comment]
> I dumped out the response from line 82. Here is the response.
> <img alt="Screenshot 2023-07-23 at 20 03 09" width="770" src="https://user-images.githubusercontent.com/29255728/255416724-0254aff0-63b5-4190-ad9a-215b2824b6a0.png">

I suggest you start by debugging Twitter response.

**Comment by topclaudy** [comment]
I can't debug the error. This seems to work now without change in my code. As I said, it's intermittent in my situation and this start happening after upgrading to v8.

**Comment by christophrumpel** [comment]
Hey, with all the changes on Twitter API, it is often really difficult to debug issues because, aus you said, sometimes it just works again. For me it sounds like a problem with the app and credentials on the Twitter side, but if it keeps coming back, please post here again, and also the API response from Twitter so I can help debug. All the best 👍

**Comment by topclaudy** [comment]
Problem persists!! Text-only tweets work fine. Tweets with image(s) result in error. All attempts failed yesterday.

**Comment by christophrumpel** [comment]
Hey, sorry to hear that. Have you checked what the Twitter response is? This would help with debugging. (see messages above where to dump the Twitter response)

**Comment by topclaudy** [comment]
Here is the response:
_The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview._

I ran a job to post 2 notifications. The first one ALWAYS succeed. The second one results in this error. It looks like a problem when posting more than one tweets within 1 second.

**Comment by topclaudy** [comment]
> Here is the response: _The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview._
> 
> I ran a job to post 2 notifications. The first one ALWAYS succeed. The second one results in this error. It looks like a problem when posting more than one tweets within 1 second.

It keeps happening even when I pause for 15 seconds before the second tweet.

**Comment by christophrumpel** [comment]
Thanks for the update. I can take a look tomorrow.

**Comment by christophrumpel** [comment]
I tried it with the underlying Twitteroauth package and there I made it work to send a text and image.

@Nelwhix could you maybe take a look at this issue and see if you can tweet a text and image with this package?

**Comment by Nelwhix** [comment]
Okay

**Comment by Nelwhix** [comment]
I just tried posting three tweets consecutively with image and it succeeded. The error message `The Twitter REST API v1 is no longer active. Please migrate to API v1.1`. is strange because the package uses twitter API v1.1 for media upload. maybe if we could have more details of his setup so we know what could trigger the issue

**Comment by christophrumpel** [comment]
Thanks a lot @Nelwhix. 🙏 The issue might be connected to the app 🤔

@topclaudy have you tried to create a new Twitter app with new credentials? Could be an issue if the app already exists longer.

**Comment by topclaudy** [comment]
Hi @christophrumpel 
I created a new app and the error persists (same error: _The Twitter REST API v1 is no longer active..._). The new credentials from the new app work for Laravel Socialite tough. This is weird!

**Comment by christophrumpel** [comment]
This is really strange =/ I also ran into a few issues with Twitter where I do not why they do not work.

The app is also within a "project" on the Twitter developer page?

**Comment by topclaudy** [comment]
Yes! The app is within a project.

**Comment by topclaudy** [comment]
I noticed that the 2 consecutive tweets (with image) were posted successfully in the first attempt just after creating the new app/credentials. But the subsequent attempts failed.

**Comment by christophrumpel** [comment]
This sounds really weird. At this point I'm not sure how or if I can help.

What you could do is check out the package that we use under the hood: https://twitteroauth.com/
You could test if it works with this package, I use just that package in some projects too, because it is quite easy to use too.

**Comment by topclaudy** [comment]
@christophrumpel Thanks for the tips. It looks like a problem on Twitter... Oops! X. I'm gonna close this issue.

**Comment by topclaudy** [comment]
This was definitely an issue with the package. I updated to the last version and this issue is solved.
